[package]
authors = ["Liu Hao <liuhao@nets.com.sg>"]
edition = "2018"
name = "frontend"
version = "0.1.0"
[dependencies]
anyhow = "*"
serde = "*"
wasm-bindgen = "0.2.67"
yew = "*"
yew-router = "*"

[lib]
crate-type = ["cdylib", "rlib"]
